In [1]:
from IPython.core.interactiveshell import InteractiveShell
InteractiveShell.ast_node_interactivity = "all"
import numpy as np
from sklearn.linear_model import SGDClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.svm import LinearSVC                  
import pandas as pd

ModuleNotFoundError: No module named 'sklearn'

In [ ]:
import pandas as pd
#IMPORTING DATASET
data=pd.read_csv("D:/train.csv",header=0)
data.head()

id                                               name  \
0  22474  Information Regarding the Merger of Navios Mar...   
1  27460  Announcement on Approving the Change of Member...   
2   6926          SFC Suspends Shiu Yau Wah for Five Months   
3   6982            Renminbi RMB Haircut - February 4, 2020   
4   5022  Anti-Money Laundering, Countering Financing of...   

                                       document_text                  cat_name  
0  At a special meeting held on March 24, 2021 sh...  Corporate Communications  
1  On April 2, 2021, the China Financial Futures ...     Securities Settlement  
2  The Securities and Futures Commission (SFC) ha...                 Antitrust  
3  Pursuant to Section 2.6.2 of the Clearing Hous...     Securities Settlement  
4  Money laundering and terrorism financing (ML/T...           Financial Crime

In [71]:
#GROUPING BY THE DATA WITH RESPECT TO ID AND DOCUMENT_TEXT AND CONCATENATING THE VALUES IN CAT_NAME COLUMN
data_2 = data.groupby(['id','document_text'])['cat_name'].apply(','.join).reset_index()


In [72]:
data_2

id                                      document_text  \
0      4772  Solium Financial Services LLC ("SFS") is a bro...   
1      4774  A new year brings new investment opportunities...   
2      4775  The Alberta Securities Commission (ASC) has co...   
3      4776  The Canadian Securities Administrators (CSA) p...   
4      4778  On April 6, 2017, the Canadian Securities Admi...   
...     ...                                                ...   
9854  57201  Having a good track record when it comes to me...   
9855  57207  The Bank of Russia has decided, starting from ...   
9856  57234  Consob published application of a pecuniary ad...   
9857  57240  On May 31, 2022, Shenzhen Stock Exchange publi...   
9858  57252  Effective Monday, June 13, 2022, Chicago Merca...   

                                               cat_name  
0     Licensure and certification,Definitions,Licens...  
1     Market Risk,Regulatory Actions,Fraud,Financial...  
2     Securities Settlement,Trade Settlement,Licensu...  
3     Securities Settlement,Required Disclosures,Leg...  
4     Consumer protection,Regulatory Reporting,Deliv...  
...                                                 ...  
9854                Financial Crime,Consumer protection  
9855  Payments and Settlements,Securities Settlement...  
9856  Examinations,Regulatory Reporting,Accounting a...  
9857        Securities Issuing,Corporate Communications  
9858            Commodities Trading,Contract Provisions  

[9859 rows x 3 columns]

In [73]:
#MAKING A LIST OF CATEGORY NAMES AND A LIST OF DOCUMENTS
cat_name_list = [x.split(',') for x in data_2['cat_name'].tolist()]
doc_list = data_2['document_text'].values.tolist()

In [78]:
#DOING ONE HOT ENCODING OF THE CATEGORIES
from sklearn.preprocessing import MultiLabelBinarizer
import numpy as np

mlb = MultiLabelBinarizer()

Y=mlb.fit_transform(cat_name_list)
# check size of indicator matrix
# print some rows 
Y[0:5]
Y.shape
# check classes
mlb.classes_
print('docs shape',len(doc_list), 'y shape',Y.shape)



array([[0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0],
       [0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0,
        1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 1, 1, 0, 1],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0,
        0, 0, 0, 1, 0, 0],
       [0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0,
        0, 0, 0, 1, 0, 0]])

(9859, 50)

array(['Accounting and Finance', 'Antitrust', 'Banking', 'Broker Dealer',
       'Commodities Trading', 'Compliance Management',
       'Consumer protection', 'Contract Provisions',
       'Corporate Communications', 'Corporate Governance', 'Definitions',
       'Delivery', 'Examinations', 'Exemptions', 'Fees and Charges',
       'Financial Accounting', 'Financial Crime', 'Forms', 'Fraud',
       'IT Risk', 'Information Filing', 'Insurance', 'Legal',
       'Legal Proceedings', 'Licensing', 'Licensure and certification',
       'Liquidity Risk', 'Listing', 'Market Abuse', 'Market Risk',
       'Monetary and Economic Policy', 'Money Services',
       'Money-Laundering and Terrorist Financing', 'Natural Disasters',
       'Payments and Settlements', 'Powers and Duties', 'Quotation',
       'Records Maintenance', 'Regulatory Actions',
       'Regulatory Reporting', 'Required Disclosures', 'Research',
       'Risk Management', 'Securities Clearing', 'Securities Issuing',
       'Securities

docs shape 9859 y shape (9859, 50)


In [79]:
#MAKING TFIDF MATRIX 
from sklearn.feature_extraction.text import TfidfVectorizer

tfidf = TfidfVectorizer(stop_words="english",min_df=2)
matrx = tfidf.fit_transform(data_2['document_text'])


In [80]:
from sklearn.svm import LinearSVC
from sklearn.model_selection import train_test_split
from sklearn.multiclass import OneVsRestClassifier
#SPLITTING THE DATA INTO TRAIN AND TEST DATA
X_train, X_test, Y_train, Y_test = train_test_split(matrx, Y, test_size=0.3, random_state=0)
#FITTING THE CLASSIFER ON TRAIN DATA
clf =  OneVsRestClassifier(LinearSVC()).fit(X_train,Y_train)

In [84]:
# Multi-label classification- Performance report
from sklearn.metrics import classification_report
# PREDICTING THE TEST DATA USING THE CLASSIFIER
predicted = clf.predict(X_test)

predicted.shape
print("predicted:")
predicted[0:2]
print("actual:")
Y_test[0:2]
#PRINTING THE CLASSIFICATION REPORT
print(classification_report\
      (Y_test, predicted, target_names=mlb.classes_, zero_division = 0))

(2958, 50)

predicted:


array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1,
        0, 0, 0, 0, 0, 0],
       [0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0]])

actual:


array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1,
        0, 0, 0, 0, 0, 0],
       [0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0]])

                                          precision    recall  f1-score   support

                  Accounting and Finance       0.85      0.47      0.61       268
                               Antitrust       0.95      0.68      0.79       281
                                 Banking       0.95      0.73      0.83       317
                           Broker Dealer       0.91      0.73      0.81       198
                     Commodities Trading       0.93      0.85      0.89       199
                   Compliance Management       0.94      0.66      0.77       443
                     Consumer protection       0.90      0.64      0.75       292
                     Contract Provisions       0.90      0.69      0.78       345
                Corporate Communications       0.80      0.45      0.58       163
                    Corporate Governance       0.79      0.55      0.65       277
                             Definitions       0.91      0.54      0.68       175
               

In [90]:
# CREATED A FUNCTION TO CALCULATE THE HAMMING SCORE WHICH INDICATES THE ACCURACY FOR MULTI-LABEL CLASSIFICATION
def hamming_score(y_true, y_pred):

    acc_list = []
    for i in range(y_true.shape[0]):
        true_set = set( np.where(y_true[i])[0] )
        predicted_set = set( np.where(y_pred[i])[0] )
        tmp_a = None
        if len(true_set) == 0 and len(predicted_set) == 0:
            tmp_a = 1
        else:
            tmp_a = len(true_set.intersection(predicted_set))/\
                    float( len(true_set.union(predicted_set)) )
        acc_list.append(tmp_a)
    
    return np.mean(acc_list)

hamming_score(Y_test, predicted)

0.5944778716226037

In [95]:
# CALCULATING THE JACCARD SCORE WHICH INDICATES THE ACCURACY FOR MULTI-LABEL CLASSIFICATION
from sklearn.metrics import jaccard_score
j_score = jaccard_score(Y_test, predicted, average = 'samples')
j_score

0.5944778716226037

In [91]:
#CALCULATING HAMMING LOSS WHICH SHOWS THE FRACTION OF LABELS THAT ARE INCORRECTLY PREDICTED
from sklearn.metrics import hamming_loss
hloss = hamming_loss(Y_test,predicted)
hloss

0.04079107505070994

In [54]:
x = ['Commission de Surveillance du Secteur Financier (CSSF) updated questions and answers with regard to Covid-19. The questions are regarding: Can Less Significant Institutions temporarily exclude certain exposures to central banks from the leverage ratio calculation pursuant to Article 500b of Regulation (EU) 575/2013 as amended in the context of the COVID-19 pandemic; Can the remuneration benchmarking exercise of the European Banking Authority (EBA) be postponed; Can the data collection exercise regarding high earners by the European Banking Authority (EBA) be postponed; Can the deadlines for the submission of the closing documents of specialised PFS be postponed; What is the general prudential treatment of a moratorium and how should it be applied to COVID-19 private industry-wide moratoria; How can institutions invoke the dedicated prudential treatment related to the COVID-19 private industry-wide moratoria; What are the consequences on the phasing-out of EBA-eligible payment moratoria; What is the CSSF’s position concerning the deadlines applicable under the UCITS Directive and under the AIFMD for annual and half-yearly reports; What is the flexibility offered by IFRS 9 in order to mitigate volatility in the banks’ regulatory capital, financial statements and reporting of the banks regarding the COVID-19 pandemic; What is the CSSF policy stance as regards banks’ distribution policies aimed at remunerating shareholders, as well as on variable remuneration in the COVID-19 context; Can the deadlines for the reports to be submitted by payment institutions and electronic money institutions be extended; Can the deadlines for the reports to be submitted by the investment firms be extended; Can the deadlines for the reports to be submitted by the support PFS be extended; What are the purpose and the main elements covered in the publications of the EBA dated March 25, 2020 in the context of COVID-19; Can the deadlines for the reports to be submitted by the banks be extended; Temporary waiver of prior authorisation/notification requirements for cloud-based outsourcing; Can UCIs (UCITS, UCI Part II & SIFs) increase the swing factor to be applied on the NAV up to the maximum level laid down in the prospectus; the ECB has communicated on a number of measures to alleviate the impacts of COVID-19 on Significant Institutions, will Less Significant Institutions also be able to benefit from similar measures; Does the recommendation made to financial institutions subject to the CSSF’s prudential supervision to favour work from home in the framework of their business continuity plan; and what are the minimum IT security conditions recommended for remote access']

In [55]:
dtm_test = tfidf.transform(x)

In [57]:
clf.predict(dtm_test)

array([[1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0,
        0, 0, 0, 0, 0, 0]])

In [68]:
#mlb.classes_

In [58]:
mlb.inverse_transform(clf.predict(dtm_test))

[('Accounting and Finance',
  'Banking',
  'Fees and Charges',
  'Financial Accounting',
  'Information Filing',
  'Money Services',
  'Natural Disasters',
  'Regulatory Reporting',
  'Required Disclosures')]